name: Create Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-image:
    runs-on: ubuntu-latest
    needs: login

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean package

      - name: Get the version number from tag
        run: echo "VERSION_NUMBER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: josejuanhernandez/ulpgc:${{ env.VERSION_NUMBER }}
